### ISSUE TITLE
Item duplicate in Forge and Bukkit mixed Server

### ISSUE THREAD

**Issue by qyl27** [blay09/TrashSlot#101]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.59

### Mod Version

11.0.1

### Describe the Issue

I am using a Bukkit and Forge mixed Server core named [Arclight](https://github.com/IzzelAliz/Arclight).
I found an item duplicate bug with the Bukkit plugin [QuickShop](https://www.spigotmc.org/resources/quickshop-reremake-1-18-ready-multi-currency.62575/).

When I use the "preview sale item" feature in QuickShop, it will show me a GUI with some item in Shop, that should not be moveable, but when I pressed `Delete` (The default Key of delete item in TrashSlot), the item which shouldn't be moveable was transferred to the trash slot in GUI.
Then close the GUI and open my backpack, the item in the trash slot can click and move to my backpack now.

So I think this will cause duplicate items.

The author of Arclight said, it was caused by TrashSlot Mod, this mod use their method to move item between gui.
See [IzzelAliz/Arclight#505](https://github.com/IzzelAliz/Arclight/issues/505) for more information.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by BlayTheNinth** [comment]
TrashSlot is not compatible with Bukkit plugins. Since server-side plugins simulate these slots without making them actually "unpickupable", there is no way for TrashSlot to know whether it's a real slot or a fake one.
