### ISSUE TITLE
Add the option to turn on the trash slot only in creative mode

### ISSUE THREAD

**Issue by EGOIST1372** [blay09/TrashSlot#103]
Add the option to turn on the trash slot only in creative mode. since creative mode has this annoying trash slot that you need to click 2 times to reach it and it would be great to have it even when you searching for items in creative mode

**Comment by BlayTheNinth** [comment]
I don't really see the use case - either you're on the inventory tab and have the Vanilla trash slot to drop items into, or you're on a creative tab where the only items you could delete are on your hotbar, and you can simply drop them into the creative slots to delete. It doesn't really feel worth the effort of making the movable TrashSlot play and snap nice with the tabs around the window when deletion is already supported by Vanilla in this case.
