### ISSUE TITLE
mod fails to load on the newest version of forge

### ISSUE THREAD

**Issue by Itsironicxx** [blay09/TrashSlot#109]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

41.0.91

### Mod Version

12.0.0

### Describe the Issue

gives a failed to load message when starting on the newest version of forge

**Comment by BlayTheNinth** [comment]
Update Balm to latest version ...

**Comment by Itsironicxx** [comment]
bruh, thanks lol
