### ISSUE TITLE
trashlot 1.19.3 doesn't show

### ISSUE THREAD

**Issue by saralup** [blay09/TrashSlot#119]
### Minecraft Version

1.19.3

### Mod Loader

Fabric

### Mod Loader Version

newest

### Mod Version

newest 1.19.3

### Describe the Issue

not show anywhere

**Comment by BlayTheNinth** [comment]
There's a keybind to toggle it, by default it only shows up on the vanilla inventory. If you have a mod installed that modifies the inventory, you may have to specifically enable it using the keybind first.

**Comment by BlayTheNinth** [comment]
It could also be that you're using ReplayMod. A fix just went out for 1.18.2, 1.19.2 and 1.19.3 that fixes ReplayMod compatibility.

**Comment by saralup** [comment]
now it was fixed,thank you ,good job



saral
***@***.***







                       
Original
                       
                     

From:"BlayTheNinth"< ***@***.*** &gt;;

Date:2023/2/26 23:46

To:"TwelveIterationMods/TrashSlot"< ***@***.*** &gt;;

CC:"saralup"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [TwelveIterationMods/TrashSlot] trashlot 1.19.3 doesn't show(Issue #119)




 
Closed #119 as completed.
