### ISSUE TITLE
Option to move trash slot inside the window

### ISSUE THREAD

**Issue by HySand** [blay09/TrashSlot#120]
Or move if No Recipe Book installed

**Comment by BlayTheNinth** [comment]
I don't know what this means, the trash slot can already be dragged around the screen.

**Comment by HySand** [comment]
Is it possible to move the slot in the inventory instead of around it?
<img width="561" alt="2023-03-01 224434" src="https://user-images.githubusercontent.com/77628540/222176858-660d80dd-d03b-4787-8399-509586fd4f41.png">

**Comment by BlayTheNinth** [comment]
This is extremely unlikely to be implemented as the effort, usability and actual use cases are way out of balance. It would only really be possible on the inventory screen and no other screens, and even there still carry a high risk of conflicts with other mods that alter the screen. It also wouldn't be the most intuitive to control and likely end up hidden behind a config option that only very few people enable. Moving this to Discussions for now.
