### ISSUE TITLE
Option to allow deleting items while trash slot is not visible

### ISSUE THREAD

**Issue by JustKenjiX** [blay09/TrashSlot#121]
When you hide the trashslot I would love to have an option to be able to delete items from your inventory with the 'delete key'. For now you can't delete more items after the first item is in the slot. 

The best option would be with a query 'Do you really want to delete this item?' - 'Yes' or 'No' for not delete an item by mistake.

Maybe this is a bit over the top for a trashslot mod but it would be an awesome addition.

**Comment by BlayTheNinth** [comment]
If this gets implemented, there would not be a confirmation query for this, it would simply be an option (default off) that makes the deletion keybinds work even if the trash slot is not visible.

**Comment by JustKenjiX** [comment]
I can understand that such a query is not so easy to integrate. Wanted to note it here anyway. I thought that such a feature might appeal to you and this mod.
Thanks for taking a look at my original feature request to delete items with a config key even with the slot not visable. 🙂
