### ISSUE TITLE
Trash Slot doesn't work with Tiny Item Animations mod

### ISSUE THREAD

**Issue by Treeways** [blay09/TrashSlot#123]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### Mod Version

12.0.2

### Balm Version

4.5.7

### Describe the Issue

The Tiny Item Animations (TIA) mod doesn't work with the Trash Slot.

It seems that TIA is implemented in a way that would affect any normal item slots in Minecraft. Is the trash slot implemented in a different way?

TIA is on version 1.19.2-1.0
See https://github.com/Trivaxy/Tiny-Item-Animations/issues/4

TIA is responsible for the little item growing animation when clicked from the hotbar:

https://user-images.githubusercontent.com/56928485/239615774-667497c4-316e-4155-b7b2-5c81b0470e41.mp4

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Tested with TrashSlot, Tiny Item Animations, Balm and ModernFix

**Comment by BlayTheNinth** [comment]
The trash slot is not a regular slot since it can be added to any container screen, which couldn't safely be done as a regular slot without risking other mods running into unpredictable issues.
