### ISSUE TITLE
Add a dark theme for the trash slot, for compatibility with Inventorio mod dark theme option.

### ISSUE THREAD

**Issue by akai-hana** [blay09/TrashSlot#127]
Inventorio is an inventory mod that has a dark mode inventory option, so the trash slot looks out of place when this option is enabled.

![image](https://github.com/TwelveIterationMods/TrashSlot/assets/55887501/f141f7ac-40ce-4223-ac34-28078db2bb30)

Even if it's not for the purpose of compatibility with this mod, adding an option for a dark-themed trash slot would also be appreciated stand-alone.

**Comment by Nekiplay** [comment]
Modify slot texture by Resource pack

**Comment by BlayTheNinth** [comment]
Yeah, using a resource pack is the way to go. There is no one unified "dark mode" that TrashSlot could adhere to, and adding support for every individual mod would be way out of scope. There is also a mod [Dark Mode Everywhere](https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere) that works correctly on TrashSlot I believe.
