### ISSUE TITLE
Waystones and Trashslots both got

### ISSUE THREAD

**Issue by Ryuushen** [blay09/TrashSlot#128]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

1.18.2

### Mod Version

1.18.2

### Balm Version

3.2.6

### Describe the Issue

Sorry to put both mods here but since you made them both I thought it might have something to do with Balm.
Forge: 40.2.14
MC: 1.18.2
Trashlot Mod ver: 11.0.3
Waystones Mod ver: 10.2.2
Balm: 3.2.6

I installed both mods exact same on server and it works great. However, after disconnect and reconnect or restart client or restart server. All the waystones would not show activated. And if you activated 1, the list doens't show anything. It only works after I break the waystone, and replace it back then I will see all the other waystones.

The 2nd problem is trashslot. At first login it wont shows trash slot and notice that server is not install trash slot blah blah. But then after I die and comeback, the trashslot will show up normally.

I have no idea what could be the cause

**Comment by BlayTheNinth** [comment]
Does this happen in more recent versions? 1.18.2 is no longer supported.

**Comment by Ryuushen** [comment]
> Does this happen in more recent versions? 1.18.2 is no longer supported.

Ahh i dont know that, I just play 1.18.2 cause Ice and Fire rn :C
