### ISSUE TITLE
Failure To Load On Startup NeoForge 20.4.89 Beta (1.20.4)

### ISSUE THREAD

**Issue by Omogen** [blay09/TrashSlot#129]
### Minecraft Version

1.20.4

### Mod Loader

NeoForge

### Mod Loader Version

1.20.4

### Mod Version

20.4.89

### Balm Version

9.0.4

### Describe the Issue

Upon starting Minecraft, NeoForge notes that TrashSlot failed to load. No other mods installed other than dependency.

### Logs

https://pastebin.com/CMRZnZw2

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

No.

**Comment by BlayTheNinth** [comment]
Balm is not yet compatible with NeoForge's networking rewrite, you would have to use an older version of NeoForge for now.

**Comment by BlayTheNinth** [comment]
Fixed in Balm 9.0.5+
