### ISSUE TITLE
Incompatible with Flow

### ISSUE THREAD

**Issue by Jakobabs** [blay09/TrashSlot#130]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Mod Loader Version

0.15.6

### Mod Version

16.0.1

### Balm Version

9.0.5

### Describe the Issue

Trashslot is hidden either off screen or under the UI when using it with the mod Flow.
Flow animates all UI openings, which is where I think the issue is. Toggling it to show allows hotkey deletion, but the slot is still hidden somewhere

**Comment by Jakobabs** [comment]
Link to other mod: https://github.com/IMB11/Flow

**Comment by BlayTheNinth** [comment]
Please report this to the Flow mod - they probably have a better idea of what might be going wrong and can pinpoint the issue easier. If there is something specific I can do on TrashSlot's side, I'll be happy to follow up.
