### ISSUE TITLE
Server logs an error every minute: Tried to load invalid item: 'No key id in MapLike[{}]'

### ISSUE THREAD

**Issue by rsheptolut** [blay09/TrashSlot#133]
### Minecraft Version

Other (specify below)

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

17.0.1

### Balm Version

10.3.2

### Describe the Issue

Minecraft version 1.20.6

No problems in game (except I stopped seeing my Trashslot in inventory and only see it when I interact with chests and I think with crafting table).

But server logs this periodiacally:
[20:49:10] [Server thread/ERROR]: Tried to load invalid item: 'No key id in MapLike[{}]'

Does this perhaps ring a bell? No stack trace unfortunately or maybe I don't know how to look for one.

I don't know how to troubleshoot these things so I did the only thing I knew - disabled mods until I disabled TrashSlot and it stopped happening. Reenabled and it's happening again. That's what I have for proof but I may be wrong.

I'm hosting the server on exaroton.me if it matters.

Same version of mod and balm and fabric api and fabric loader is installed on both server and my client. Repros even when I'm the only one on the server.

Doesn't really worry me too much as the game seems to be playing fine and TrashSlot is actually Trashing as expected :D

**Comment by BlayTheNinth** [comment]
Fixed in Minecraft 1.21
