### ISSUE TITLE
Compatibility with Inventory Profiles Next locked slots

### ISSUE THREAD

**Issue by VindSole** [blay09/TrashSlot#142]
When I send an item to the trash slot with Del key, sometimes I worry I will end up deleting something important like a diamond or ancient debris, that I didn't notice my mouse was hovering over, IPN has a lock slot feature on which slots cannot be modified except by mouse clicks alone, Trash slot doesn't respect this behavior so it would be nice if there was compatibility between the two mods.

**Comment by BlayTheNinth** [comment]
Inventory Profiles Next doesn't appear to have an API for testing a slot's locked state so I can't reasonably add compatibility in TrashSlot.

However, I've added a new `ItemTrashedEvent.Pre` event that TrashSlot fires which can be cancelled to prevent deletion. This event could be used by mods like Inventory Profiles to prevent deletion on protected slots.
