### ISSUE TITLE
Invisible Trash Slot

### ISSUE THREAD

**Issue by Alex-2030** [blay09/TrashSlot#144]
### Minecraft Version

1.21.1

### Mod Loader

Fabric

### Mod Loader Version

fabric-loader-0.16.4-1.21.1

### Mod Version

21.1.1+fabric-1.21.1

### Balm Version

balm-fabric-1.21.1-21.0.19

### Describe the Issue

Trash slot always invisible 
I can only see it for a split second when closing my inventory , thanks to the flow mod but I still can't use it
Only way i could use it is via the keybind (del)
This is during the flow closing animation
![image](https://github.com/user-attachments/assets/d6ef5915-581d-432c-a197-760eae01ea65)
This is in my inventory normally
![image](https://github.com/user-attachments/assets/51b28255-04b8-4abb-904c-f802b3c1532a)

### Logs

[latest.log](https://github.com/user-attachments/files/16918366/latest.log)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Sodium & iris

**Comment by BlayTheNinth** [comment]
If it only happens with Flow installed, it should be reported to the Flow mod.

**Comment by Alex-2030** [comment]
Alr then , sorry about the confusion!
