### ISSUE TITLE
Hovering inconsistency

### ISSUE THREAD

**Issue by Disketaa** [blay09/TrashSlot#149]
Minecraft hovering:
![image](https://github.com/user-attachments/assets/bff042cf-3105-4b8c-b598-8336be139038)
![image](https://github.com/user-attachments/assets/ee89a476-dfdd-4811-8953-9e9279129a14)

Trash Slot hovering:
![image](https://github.com/user-attachments/assets/f00564d9-0175-4632-8b2a-f18cb97334fd)
![image](https://github.com/user-attachments/assets/2cc6827e-cb42-4a8d-a59d-cad2ecfe0e4a)

(Trash icon doesn't hover)

**Comment by BlayTheNinth** [comment]
This should be fixed in 1.21.2 since this effect is now accomplished with a background/foreground texture in Vanilla.
