### ISSUE TITLE
Delete Key doesn't work in Creative

### ISSUE THREAD

**Issue by Apollo70** [blay09/TrashSlot#151]
### Minecraft Version

1.21.1 (LTS)

### Mod Loader

Fabric

### Mod Version

1.21.1

### Describe the Issue

The Delete Key at mouse cursor doesn't work in Creative.
I set the Delete key to \ 
It works in Survivle but in Creative it shows the notification of deleting the item but the item is still there.

### Logs

[latest.log](https://github.com/user-attachments/files/17531043/latest.log)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge or Arclight)?

No, Fabric and all the Sodium lithium phos.. stuf

**Comment by BlayTheNinth** [comment]
I can't reproduce this issue. Please provide a step-by-step guide on how to make the problem appear.
