### ISSUE TITLE
Alternative Slot Positions

### ISSUE THREAD

**Issue by blay09** [blay09/TrashSlot#2]
Some people get intimidated by the positioning of the slot. Might as well provide configurable alternate positions.

**Comment by Razorskills** [comment]
I really, really like being able to move the trashslot by clicking and dragging. I noticed when you click and drag it and it snaps on to the bottom, or the right side of the inventory. Then you close the inventory it will save it just fine and when you reopen, it will still be attached exactly how you left it.

If I instead snap it to the left side or top of the inventory. If I close it and reopen it. The trash slot will no longer be snapped to the grid, but will still be in the same location you left it.

I tested this with:
- forge-11.15.0.1703
- trashslot-mc1.8.9-2.0.7

(If you feel this should be in a separate issue, I will copy and paste it to a new issue. But I felt this was still a part of this one)
