### ISSUE TITLE
Shift + Del not working

### ISSUE THREAD

**Issue by UnPure** [blay09/TrashSlot#26]
Hey there.
I'm using v6.3.6 of this mod on 1.10.2 together with forge 12.18.2.2123.
For some reason it seems like Shift + Del is not working anymore (Only Del works fine).
I tested it completly without any other mods and its not working so its not some kind of imcompatibility.
Would be nice if you could fix that issue because i realy miss a fast way to delete all my cobble.

**Comment by UnPure** [comment]
Any chance to see this fixed in 1.10.2 too? Or is 1.10 support dropped?

**Comment by BlayTheNinth** [comment]
https://minecraft.curseforge.com/projects/trashslot/files/2350629
