### ISSUE TITLE
[1.10.2] TS dosent display when using HandyBag from Enderutilities

### ISSUE THREAD

**Issue by Morpheus1101** [blay09/TrashSlot#27]
![2016-12-04_14 05 20](https://cloud.githubusercontent.com/assets/10524952/20863998/b5b61782-ba2a-11e6-9d3f-fc1bbb29956d.png)

**Comment by BlayTheNinth** [comment]
Did you press the TrashSlot key (default T) to make it appear?

**Comment by Morpheus1101** [comment]
Pressing T does nothing to make it display for me

**Comment by BlayTheNinth** [comment]
Wait, just saw it's 1.10.2. 1.10.2 only has the trash slot appear in the player inventory. It being everywhere is 1.11+
