### ISSUE TITLE
1.11.2-7.4.3 Trashslot positioning not adjusting

### ISSUE THREAD

**Issue by SableDrake** [blay09/TrashSlot#31]
like https://github.com/blay09/TrashSlot/issues/29
just made worse by other mod's GUIs
![2017-03-30_10 09 51](https://cloud.githubusercontent.com/assets/7422727/24494349/432aedb0-1532-11e7-8cd7-c2e46ecdeefd.png)
![2017-03-30_10 10 06](https://cloud.githubusercontent.com/assets/7422727/24494354/45844084-1532-11e7-9981-5a9a67ab81b8.png)

**Comment by NovaViper** [comment]
This happens with Backpacks! v3.1.8 for 1.11.2 aswell

**Comment by BlayTheNinth** [comment]
Some mods do weird things with their GUIs which causes issues for TrashSlot, as it expects everyone to follow vanilla patterns. In this case it seems like the size is dynamically changing based on your window size. Just drag the slot to the position you want and it'll stay there.

**Comment by BlayTheNinth** [comment]
Looks like I misunderstood this issue, but it should be fixed in the latest version now (although some mod GUIs are likely still broken, they will no longer share the same slot settings as other GUIs).
