### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by ghost** [blay09/TrashSlot#32]
[backpacks!](https://minecraft.curseforge.com/projects/backpacks) mod. trash slot coming on to last slot in hotbar when open backpack. thanks.
![trashslot](https://cloud.githubusercontent.com/assets/24831406/24827926/c53d6faa-1c5b-11e7-80b2-a847e5df3807.PNG)
...

**Comment by ghost** [comment]
please help...

**Comment by BlayTheNinth** [comment]
Some mods do weird things with their GUIs which causes issues for TrashSlot, as it expects everyone to follow vanilla patterns. In this case it seems like the size is not being set correctly. Just drag the slot to the position you want and it'll stay there.

**Comment by BlayTheNinth** [comment]
Looks like I misunderstood this issue, but it should be fixed in the latest version now (although some mod GUIs are likely still broken, they will no longer share the same slot settings as other GUIs).

**Comment by ghost** [comment]
hmm... should i report it to the backpacks mod?

**Comment by BlayTheNinth** [comment]
No, it's an issue here.

**Comment by ghost** [comment]
okay.
