### ISSUE TITLE
The problem with death (spongeforge + TrashSlot)

### ISSUE THREAD

**Issue by mkrtes** [blay09/TrashSlot#34]
Hi. I use the ResonantRise modpack with a spongeforge on my server. Noticed that if I set the TrashSlot on server -  player after dies (for any reason) get this error message. 
The player is constantly dying. Sometimes can't move.

Error: http://vpaste.net/euLT0
This error is constantly spamming the console
Full log: https://gist.githubusercontent.com/mkrtes/a1171e0011d021560488beff7731728e/raw/07f675d24bfca30c75768f2649f2da0150d72f12/gistfile1.txt

Had to remove your mod. I don't know if it's your error or sponge.

**Comment by BlayTheNinth** [comment]
Sponge and likely fixed on 1.11.2.
