### ISSUE TITLE
Tinkers Construct Tables and TrashSlot broken

### ISSUE THREAD

**Issue by KageDragon** [blay09/TrashSlot#35]
Using TrashSlot_1.11.2-7.4.5\TConstruct-1.11.2-2.7.0.12

On the crafting station, the  slot is right in the middle of the gui, and the trash icon is offset.
The other tables have even more, and the slot doesn't dock.
Tried moving it, but then everything else is messed up 
Tried adjusting window size, and UI size, it's the same.

**Comment by Endmateria** [comment]
Can confirm (using same mod versions stated above)...
https://ibb.co/mNC9WQ

**Comment by BlayTheNinth** [comment]
Turns out the "real" issue was that all GUIs shared the same settings for the TrashSlot, so moving them in one would also move them in another, and as a result, the TrashSlot would be enabled for all screens by default (even though it was meant to be 'turn on at your own risk' thing for mod GUIs).
