### ISSUE TITLE
List of incompatible mod GUIs

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/TrashSlot#37]
**Note: Generally you can enable the TrashSlot in every container GUI by pressing the keybind (by default: T).** 

This is a list of GUIs where the trash slot is known to not adapt to the GUI well, and therefore use of it within these is not recommended.

* Tinkers Construct
* Actually Additions' Crates
* Backpacks!
* RF Tools Modular Storage
* Engineer's Decor

**Comment by Leosky** [comment]
could a Ender Utilities compatibility possible (with the handy bag) ?

**Comment by huntzilla360c** [comment]
with dank storage, the trash slot is behind the UI and takes over these two. I cannot transfer anything to/from, either by shift-clicking or drag n' drop. and i can pull the last trashed item from there but not put it back

![1596215282202](https://user-images.githubusercontent.com/61102631/89059291-ec061780-d32e-11ea-8c60-e454fce16fc6.JPEG)

**Comment by Andr0oS** [comment]
Getting a crash to desktop every time I use the trash slot in Dank Storage (3.11) with Trash Slot (12.2.0) in ATM6 (forge 34.1.23)

> with dank storage, the trash slot is behind the UI and takes over these two. I cannot transfer anything to/from, either by shift-clicking or drag n' drop. and i can pull the last trashed item from there but not put it back

If it's hidden in the largest dank storage inventory, try opening a smaller dank and moving it to the side first.

**Comment by Pingu-Pox** [comment]
Adding Quark Oddities backpack to this list, can't use trashslot or hotkeys when the backpack is equipped.

**Comment by darkqueen1229** [comment]
Replay Mod as well.
