### ISSUE TITLE
Trash slot can be used as soulbound storage slot

### ISSUE THREAD

**Issue by Laike-Endaril** [blay09/TrashSlot#45]
If instant delete is turned off and you die with an item in the trash slot, you can take it back out after respawning.  This allows some expoits (for now I've turned instant delete on for my modpack).

**Comment by Laike-Endaril** [comment]
Sorry, my mistake.  It was just one of those inventory GUI bugs; the item could be taken out of the trash slot and put in a normal inventory space, but after that any interaction with the item made it disappear (the item didn't actually exist in inventory anymore).

Wish they'd fix that ghost item bug in vanilla....sorry for the false alarm.

**Comment by Brycey92** [comment]
Is there any way for this ghost item issue to be resolved in the mod?

**Comment by Laike-Endaril** [comment]
Since this issue is already closed, I'm not even sure if Blay will get a notification of your post here.  I did, but that's because I've posted in it.

Might be better to open a new issue, maybe something like "Ghost item in trash slot after death".

**Comment by Brycey92** [comment]
Good idea! I'll open a new issue now.
