### ISSUE TITLE
Thermal Strongbox positioning

### ISSUE THREAD

**Issue by Slyklaw** [blay09/TrashSlot#46]
Thermal Expansion Strongbox has 4 levels of chest sizes. TrashSlot doesn't adjust positioning based on the size of the Strongbox.

**Comment by BlayTheNinth** [comment]
I don't believe there is a Strongbox in modern versions of Thermal Expansion, but in general, TrashSlot will only play nice with "static" / predictable screens. The TrashSlot API supports for customizing this based on screen properties (as is done for the Vanilla double chest), but with how deeply integrations would have to interact with other mod code to achieve that, I believe any integration of this kind should either be done in a separate addon or mod or in the unsupported mod itself.

See also https://github.com/TwelveIterationMods/TrashSlot/discussions/107 for a list of unsupported mods.
