### ISSUE TITLE
Adding trash slot to a new inventory doesn't save.

### ISSUE THREAD

**Issue by WenXin20** [blay09/TrashSlot#61]
`Minecraft v1.14.4`
`Forge v28.1.26`
`Trash Slot v10.4.7`

If I press `t` to add the trash slot to an inventory that did not previous have one, and then exit the world and close the game, then next time I load up the world, the inventory will not have the trash slot anymore.

**Comment by BlayTheNinth** [comment]
Waiting on https://github.com/MinecraftForge/MinecraftForge/issues/6211

**Comment by BlayTheNinth** [comment]
Will be saving this state in a separate file instead of in the config, but moving this up to 1.15.
