### ISSUE TITLE
The textures don't change with the change of texture packs

### ISSUE THREAD

**Issue by sepsol** [blay09/TrashSlot#62]
This is Trash Slot mod:
![image](https://user-images.githubusercontent.com/47871887/67152218-9819cd00-f2de-11e9-979d-52ff5cf9efbf.png)

This is Filters mod:
![image](https://user-images.githubusercontent.com/47871887/67152234-d8794b00-f2de-11e9-9ef7-ecb12d33b315.png)

And this is World Handler mod:
![image](https://user-images.githubusercontent.com/47871887/67152251-0c547080-f2df-11e9-8fa4-530bd52f4501.png)

**Comment by BlayTheNinth** [comment]
As the slot is a custom graphic (just like many other mod GUIs, such as the background of the World Handler mod you showed), it will only match the texture pack if the texture pack (or an addon for it) comes with a replacement graphic for it.

**Comment by sepsol** [comment]
So it's up to the texturepack artist to address it right?

**Comment by BlayTheNinth** [comment]
Yup

**Comment by sepsol** [comment]
Thanks :(
