### ISSUE TITLE
[1.14.4] Can't delete item using hotkey

### ISSUE THREAD

**Issue by WC9595** [blay09/TrashSlot#66]
Minecraft Version: 1.14.4
Forge Version: 28.1.87
TrashSlot Version: 10.4.7

Can't delete item using hotkey when you have instant delete config set to true.
I don't know is that a bug or what.
If I set it back to no instant delete, everything is fine.

**Comment by BlayTheNinth** [comment]
This was intentional, but I guess if you enable Instant Deletion you like to live dangerously anyways, so might as well allow it.
