### ISSUE TITLE
[1.15.2] Mod Interaction - Curios

### ISSUE THREAD

**Issue by TheUntamed** [blay09/TrashSlot#73]
Opening the Curios Inventory removes the Trash Slot.
![Screenshot_1](https://user-images.githubusercontent.com/48363903/79311287-8025ad80-7efd-11ea-8dd0-6b46cb47e6fe.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/48363903/79311292-8156da80-7efd-11ea-9f4c-b9f3b51c1e27.jpg)

I opened a issue at Curios github
https://github.com/TheIllusiveC4/Curios/issues/47#issuecomment-613846300
and they said they cannot fix it and the Slot have to be added to their inventory as well.

**Comment by BlayTheNinth** [comment]
Try pressing T to toggle the Trash Slot. The slot works in nearly every inventory GUI.

**Comment by TheUntamed** [comment]
Is it possible to enable it by default?

**Comment by BlayTheNinth** [comment]
Currently only by shipping the TrashSlot.json in the modpack. #74
