### ISSUE TITLE
TrashSlot not loading

### ISSUE THREAD

**Issue by ClaudiusMinimus** [blay09/TrashSlot#75]
I'm using your TrashSlot mod for my pack. Looking at the log, it seems to be present, but it does not load (see screenshot below).

- OS: Linux Mint 19.3
- Minecraft: 1.15.2
- Forge version: 31.1.88
- TrashSlot_1.15.2-11.0.0

https://paste.ee/p/qLgWO

![2020-05-14_22 09 07](https://user-images.githubusercontent.com/17887664/82010565-ad19cd00-962f-11ea-8b7e-beea5ae7b5e7.png)

**Comment by BlayTheNinth** [comment]
There's a keybind to toggle it, it's probably toggled off right now.

**Comment by ClaudiusMinimus** [comment]
Yup, that was it. Thanks!
