### ISSUE TITLE
[1.16.1] Crash while picking item out of slot / dropping it in the slot

### ISSUE THREAD

**Issue by UnPure** [blay09/TrashSlot#77]
While testing around on 1.16.1 I deleted an item with the keybind and tried to pick it out of the slot which results in a [crash](https://pastebin.com/DeAL7kCR). After the client restarted, the item in the trashslot was gone. I tried to drop another item directly into the slot without keybind and the client [crashed again](https://pastebin.com/81ckGEdC). The crashlogs were created together with multiple other mods but I was able to recreate both crashes with only Trashslot 12.0.0 installed on forge 32.0.66. If any other informations are required please let me know.

- MC: 1.16.1
- Forge: 32.0.66
- Trashslot: 12.0.0

**Comment by Bass2style** [comment]
i had a similar issue with the same crash, but not exactly the same walktought.
in my case, i deleted an item using the keybind without issue, and when i wanted to delete a second item, game as freezed and crashed.
i really think that the both crashes are related.

here is my crashlog : https://pastebin.com/qDznHdBr

edit : i reloaded my world, and when going in my inventory with the Inventory key, last deleted item seems disapaired from the slot, like the OP says, but, when you open another inventory that can use TrashSlot (a barrel, in my case), item appairs back in the slot, and the game crashs.
the crashlog is litteraly the same, but here is the second crashlog : https://pastebin.com/1KkTPtAd
