### ISSUE TITLE
Suggestion: Allow trashslot to always show

### ISSUE THREAD

**Issue by choekstr** [blay09/TrashSlot#84]
It seems like I am constantly having to hit the hotkey to show trashslot because it autohides all the time (presumably so it doesn't impact the normal inventory.  Would it be possible to have a setting or hotkey to keep it on no matter what?  Me personally I don't mind when it overlays other gui's as I can still use it, I just would love to stop having to hit the hotkey to show it when I need it the most and it has decided I don't need it. :)

**Comment by BlayTheNinth** [comment]
Does it autohide on the same GUI screen after you've already enabled it once? You have to "opt-in" to the TrashSlot for every GUI at least once, but it should then remember that. So if you've enabled it for chests once, it should show up for all future times you open chests too.

Also, what version is this on?

**Comment by choekstr** [comment]
ahh, ic, so it's everything I'm in.  Got it.  So chests, enable it, it stays.  backpack, then pocket storage, then infuser, then mechanical user, etc.  Tedious but I can indeed work with this, thanks for pointing this out.  Seems like it was either randomly showing up but mostly just never there when I needed it.  Appreciate the response!

And version 12.2.1 btw.
