### ISSUE TITLE
Duplication bug with 1.16.5

### ISSUE THREAD

**Issue by Capt-efficiency** [blay09/TrashSlot#86]
I've been getting a dupe bug with this mod in a mod pack I'm playing (TNP Limitless 3).

The majority of the time I've put something in the trash slot and close the inv/crafting screen it throws the same item on the floor and it's still in the trash slot as well. 

I'm not sure if it's a sync issue or what, I'm still investigating, I just wanted to let you know.

Im playing a solo world if that matters. 
Thanks.

**Comment by BlayTheNinth** [comment]
This is probably just a desync and the same as #87. Not sure why the item is falling through the GUI and can't reproduce it myself. Only happens to some users, so it's probably some mod conflict involving some user-specific context.
