### ISSUE TITLE
[1.16.5] Item in Trash Slot is dropped when inventory closes, for some

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/TrashSlot#87]
Original report: https://github.com/NillerMedDild/Enigmatica6/issues/1093

I've had players report that items in the Trash Slot are dropped when they close their inventory. I cannot reproduce it, but several have encountered it.

### Versions
- TrashSlot_1.16.3-12.2.1
- Forge-1.16.5-36.0.9

**Comment by BlayTheNinth** [comment]
Closing since there hasn't been any other reports of this happening
