### ISSUE TITLE
Wrong position/color in the inventory UIs of Engineer's Decor.

### ISSUE THREAD

**Issue by Mooncat25** [blay09/TrashSlot#88]
### **Description**
The trash slot is at wrong position when the Labeled Crate from the Engineer's Decor mod is opened. Treated wood from Immersive Engineering is needed for making the Labeled Crate, so IE is also in the list of mods for reproducing this issue.

![2021-03-08_16 19 40](https://user-images.githubusercontent.com/7956390/110294531-f1e17b00-802a-11eb-915b-de1b67a28ceb.png)

### **Mods**
Minecraft 1.16.5
Forge 36.0.46
Engineer's Decor 1.16.4-1.1.9 ([Link](https://www.curseforge.com/minecraft/mc-mods/engineers-decor))
Immersive Engineering 1.16.5-4.2.2-132 ([Link](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering))
Trash Slot 1.16.3-12.2.1

### **Steps to Reproduce**
1. Make a Labeled Crate and place it on the ground.
2. Make sure the trash slot is enabled.
3. Open the Labeled Crate by right-clicking it. Observe.
Note: if you open an Immersive Engineering storage crate before doing step 3, the trash slot is not shown. In that case, you'll have to open your inventory then do step 3.

### **Expected Behaviours**
Either the trash slot is at the correct position and does not overlap the inventory, or it is disabled for the Labeled Crate, just like the storage crates from IE.

**Comment by Mooncat25** [comment]
Upon further investigation, it turns out that many of the inventory UIs in Engineer's Decor also have the same positioning problem. The remaining ones are fine in position, but their UI colors don't match, e.g. 
![2021-03-09_18 58 51](https://user-images.githubusercontent.com/7956390/110461829-e9607180-810a-11eb-8745-cf5e260b7adb.png)

Here are the lists of blocks that have problematic UIs:

Wrong position + Mismatched color:
- Metal Crafting Table
- Labeled Crate
- Factory Hopper
- Factory Block Placer

Correct position but mismatched color:
- Small Laboratory Furnace
- Small Electrical Furnace
- Factory Dropper
- Small Waste Incinerator

**Suggestion**
I guess the easiest solution here is blacklisting all inventories from Engineer's Decor. To make it more compatible with other existing mods or mods in the future, IMO making the blacklist configurable is a good solution.

**Comment by BlayTheNinth** [comment]
Added to #37
