### ISSUE TITLE
TrashSlot GUI Issues

### ISSUE THREAD

**Issue by Foozey** [blay09/TrashSlot#90]
The slot disappears if something that alters the inventory is present. For example, wearing the Quark Oddities backpack makes the slot disappear. Opening the Curios window (which is just a small box that comes out to the left of the armour slots) also makes the slot disappear. If you could resolve this, that would be great! :)

**Comment by BlayTheNinth** [comment]
There's a keybind to toggle the TrashSlot in other GUIs.
