### ISSUE TITLE
Visual bug with trash slot

### ISSUE THREAD

**Issue by bozmund** [blay09/TrashSlot#96]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.5

### Mod Version

11.0.0

### Describe the Issue

There is a visual bug with trash slot not rendering behind hovered item window e.g. hovering over a sword and then you can t see how much dmg is the sword doing because trash slot is rendering over the window.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by BlayTheNinth** [comment]
For reference: The icon of the trash slot is rendering in front of the tooltip

![image](https://user-images.githubusercontent.com/1933180/147504451-11e902fd-d018-42f7-86af-98e4f814e1a5.png)
